name: newspaper_app
description: A new Flutter project.


publish_to: 'none'

version: 3.0.0+3000

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  #State Management
  get: ^4.6.6

  #Firebase
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_performance: ^0.9.2+7
  firebase_core_platform_interface: 4.8.0

  #Network
  intl: ^0.18.1
  http: ^1.1.0
  url_launcher: ^6.1.14

  #UI Operations
  flutter_screenutil: ^5.9.0
  lottie: ^1.4.3
  cached_network_image: ^3.3.0
  another_flushbar: <=1.10.28
  kartal: ^3.4.4

  #Other
  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  very_good_analysis: ^5.1.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
