// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_Ltxtfp77X2VUEgN5r1Usjx6XqMtUtk',
    appId: '1:1016038715707:web:b3f914fc0e336f2c20c71e',
    messagingSenderId: '1016038715707',
    projectId: 'mobilenewspaperapp',
    authDomain: 'mobilenewspaperapp.firebaseapp.com',
    storageBucket: 'mobilenewspaperapp.appspot.com',
    measurementId: 'G-SV92TBCP06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqcRMTztMLIf4PKNwg1e3ZLxXne3StRg',
    appId: '1:1016038715707:android:7f6d9a77d9aa6ddb20c71e',
    messagingSenderId: '1016038715707',
    projectId: 'mobilenewspaperapp',
    storageBucket: 'mobilenewspaperapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9AJmBpEyEpvpvbbswtuZUB9-DvI3554s',
    appId: '1:1016038715707:ios:66462de48e73fc2820c71e',
    messagingSenderId: '1016038715707',
    projectId: 'mobilenewspaperapp',
    storageBucket: 'mobilenewspaperapp.appspot.com',
    iosClientId: '1016038715707-c7amguvp8a18q1hv54fj8rjmcf5ovc3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.newspaperApp',
  );
}
